### PR TITLE
fix: chipper memory problem with long documents on Intel CPUs

### PR DESCRIPTION
**Pull request by ajjimeno**

### CODE REVIEW

**Comment by ajjimeno** [comment]
On an Intel machine with 16Gb of RAM and no swap, the following script will freeze the machine till the process is being killed. With the proposed changes, this would run with less memory.

```
from unstructured_inference.inference.layout import DocumentLayout
from unstructured_inference.models.base import get_model

model = get_model("chipper")
doc = DocumentLayout.from_file("sample-docs/layout-parser-paper.pdf", model, pdf_image_dpi=300) 
```

**Comment by ajjimeno** [comment]
I think the CI / test_ingest errors are due to changes in the ingestion tests and not specifically due to the changes in this PR.

**Comment by badGarnet** [comment]
confirming on intel instance this now uses reduce amount of memory (and actually can run a full pdf through where it wasn't able to due to OOM before)

**Comment by badGarnet** [comment]
and just for record this is the memory profile:

**Review by badGarnet — APPROVED** [review]

**Pull request merged**
