### PR TITLE
ci: remove ingest tests job from CI workflow

### PR DESCRIPTION
**Pull request by scanny**
**Summary**
These ingests tests have been failing for a while now and were not required for merge. As we have no immediate intention of fixing these and their value in this context is doubtful, remove them.

### CODE REVIEW

**Review by amadeusz-ds — APPROVED** [review]
LGTM

**Comment by scanny** [comment]
@amadeusz-ds I believe Crag was inclined for us to try to fix these rather than remove them.

**Comment by amadeusz-ds** [comment]
> @amadeusz-ds I believe Crag was inclined for us to try to fix these rather than remove them.

Anyone looked into this? I could work on that, but I don't see anything in the logs that might point to the source of the problem.

**Comment by qued** [comment]
Since this PR, @MthwRobinson disabled the tests, so I'm going to close this as moot for now. (Perfectly fine to reopen if we want the tests completely removed.)

**Pull request closed without merging**
